# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 936e8ecdf53a59553ecb5da92f23d1d1716b043dbe127fcde6ef44444c3293c32f1e5db8a1b5875ac8ab9f945d8fda766a5df6f2d71260bafd6bd27cd5c1d590

test:
  secret_key_base: a6949afb391df1960934d1b8620b673d897e21c2290e4ddf4e92f74b5a8a1bba77e013b4bbd5b3d555918e5da44d6ad6736a6ea1b5760d71ff948638976a1b20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
